//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyBuldingWorkout.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antreman
    {
        public int Id { get; set; }
        public int SporcuId { get; set; }
        public int HarAltGrupId { get; set; }
    
        public virtual Sporcu Sporcu { get; set; }
        public virtual HareketAltGrubu HareketAltGrubu { get; set; }
    }
}
