//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyBuldingWorkout.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HareketAltGrubu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HareketAltGrubu()
        {
            this.Antreman = new HashSet<Antreman>();
        }
    
        public int Id { get; set; }
        public int HareketGrupId { get; set; }
        public string HarAltGrupAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antreman> Antreman { get; set; }
        public virtual HareketGrubu HareketGrubu { get; set; }
    }
}
