//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyBuldingWorkout.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Olcum
    {
        public int Id { get; set; }
        public int SporcuId { get; set; }
        public int OlcumTipiId { get; set; }
        public Nullable<int> OlcumDegeri { get; set; }
        public Nullable<System.DateTime> OlcumTarihi { get; set; }
    
        public virtual OlcumTipi OlcumTipi { get; set; }
        public virtual Sporcu Sporcu { get; set; }
    }
}
